### ISSUE TITLE
Features request - add buttons

### ISSUE THREAD

**Issue by mporet** [khpylon/MachEWidget#1]
It would be nice to have lock/unlock/start buttons on the widget.

Also a couple of notes on color:

I would suggest changing the use of red, as it typically is used to indicate trouble. So for example in the case of the alarm it might make sense to use green for armed, gray for disarmed, and red for the alarm is going off. (Rather than red for disarmed)

This one is more subjective, but I think it would look a bit better to use the teal from the mach e logo as the accent color, rather than a pure green. I think it would look more cohesive, plus it would help those with colorblindness who have trouble differentiating #00FF00 AND #FF0000

Thanks again for your work on this. It's great!

**Comment by khpylon** [comment]
I've implemented the lock/unlock/start buttons on the widget.  They require 1) enabling under "Settings", and 2) a double-press to access them to avoid accidental usage.  The other requests (the color changes) are still being considered, so no changes at this time for them.

**Comment by khpylon** [comment]
Since there isn't any input from other, closing this discussion.
