### ISSUE TITLE
Bug: Android widget not updating

### ISSUE THREAD

**Issue by kreuselh** [khpylon/MachEWidget#10]

**Comment by zhackwyatt** [comment]
> mache_logfile.txt

You may want to sanitize that log file as it has some personally identifiable information.

**Comment by khpylon** [comment]
> > mache_logfile.txt
> 
> You may want to sanitize that log file as it has some personally identifiable information.

Thanks. I redacted it.

**Comment by khpylon** [comment]
So let me know if the problem is fixed with the latest update.
