### ISSUE TITLE
Widget display N/A & app crashing 

### ISSUE THREAD

**Issue by neildmc** [khpylon/MachEWidget#11]
Summary of actions:

Phone: Samsung Galaxy S21 5G, Android 12

1. Download latest APK
2. Install successful
3. Open app. Turn on logging, turn off location & app launcher options.
4. Enter VIN, u/n & password & click log in
5. Success popup displayed
6.  Download log (mache_logfile (3).txt)
7. Add widget to home screen (tried Lawnchair launcher and also Samsung Launcher). 
8. WIDGET DISPLAY N/A FOR ALL VALUES (screenshot attached)
9. Opening config app, crashes immediately w/ no error
10. Remove widget from home screen
11. Open app successful, download log (mache_logfile (4).txt)
12. 
![Screenshot_20220330-075315_Lawnchair](https://user-images.githubusercontent.com/28742452/160769768-d746c605-3a3b-4fcb-adb6-c9621edf195f.jpg)

**Comment by neildmc** [comment]
[mache_logfile (3).txt](https://github.com/khpylon/MachEWidget/files/8377785/mache_logfile.3.txt)

**Comment by neildmc** [comment]
[mache_logfile (4).txt](https://github.com/khpylon/MachEWidget/files/8377791/mache_logfile.4.txt)

**Comment by khpylon** [comment]
The issue probably has to do with your VIN and how the app figures out which widget to use. It looks like I'm not processing European VINs.

**Comment by neildmc** [comment]
Thanks, this worked on my last phone though (Xiaomi Mi 9T Pro w/ Lawnchair launcher) so the API side of things seemed to be fine? The only difference on the Xiaomi I can think of is their version of Android (MIUI) is based on Android 11, and this is running 12. Anything I can try to help?

**Comment by neildmc** [comment]
Sorry, important update I just reformatted my old phone and it's actually doing the same error. Maybe something changed in the API, or something broke coincidentally in a new version of the APK. Do you persist any of the older versions at all to check? Unfortunately I lost everything on the old phone.

**Comment by neildmc** [comment]
Figured out how to download the 2022.03.02 APK from Git and it's working fine. Not sure what could be in the new version that's breaking it for me. Will keep trying incremental versions to figure the latest which works for my phone.

**Comment by khpylon** [comment]
The problem was in how the app tries to determine what to display in the widget based on the VIN; this was a recent addition.  I was only looking at North American VINs, so it didn't know how to handle yours.  This should be fixed in the next release.
