### ISSUE TITLE
Bugs in new "profile" test implementation

### ISSUE THREAD

**Issue by sirmeili** [khpylon/MachEWidget#12]
I installed the new update you gave me (7pmish on 4/15) and it immediately crashed. Opened successfully on next attempt to open app.

Logcat:
[machewidget-logcat-04-15-19_20_04.txt](https://github.com/khpylon/MachEWidget/files/8498881/machewidget-logcat-04-15-19_20_04.txt)

**Comment by khpylon** [comment]
This ended up as a dead branch..  I/m sure there'll be other wonderful, exciting bugs in the mainline code.
