### ISSUE TITLE
Bug: App crash when opening OTA

### ISSUE THREAD

**Issue by runxmedia** [khpylon/MachEWidget#13]
[machewidget-logcat-05-02-06_20_13.txt](https://github.com/khpylon/MachEWidget/files/8603409/machewidget-logcat-05-02-06_20_13.txt)
Attached is the log file from the crash... Appears to be a null pointer exception in the async task callback

**Comment by khpylon** [comment]
I just pushed a new version with multiple null-pointer checks added.  Let me know if you're still seeing this crash.

**Comment by runxmedia** [comment]
Fixed! Thank you!
