### ISSUE TITLE
Updated Android Widget now will not work.

### ISSUE THREAD

**Issue by Ianmarcho** [khpylon/MachEWidget#16]
Hi, I had the widget working great but got an 'update available' message a couple of days ago so updated!! Now widget is frozen and if I refresh I get a failed message and fsw files saved. I'm using Android on Sumsung S20. Have attached the Fsw file.
Cheers
Ian

**Comment by khpylon** [comment]
I just released 2022.05.25.  I recommend uninstalling the last version completely, then sideloading the new one.  Respond here if that fixes the problem.
