### ISSUE TITLE
Excessive API calls causing 12V battery drains per Ford SSM

### ISSUE THREAD

**Issue by TechnicalLee** [khpylon/MachEWidget#17]
Excessive API calls for status updates may cause 12V battery drains on some 2013-2023 connected vehicles per Ford SSM 50804. Suggest lengthening the default poll interval to ≥2 hour, making it manual refresh only by default, or implementing a way to only refresh the data when the user looks at the widget. Every 5 minutes may be excessive.

**Comment by mikebaz** [comment]
The author has stated that this is not an issue with this widget.  https://www.macheforum.com/site/threads/android-widget-for-mach-e-less-complex.13563/page-17#post-427458
