### ISSUE TITLE
Ford Escape PHEV

### ISSUE THREAD

**Issue by FadingFox** [khpylon/MachEWidget#20]
The widget used to show EV miles range but now it shows gas. It would be nice to see both or be able to toggle between the two in settings or see gas range when EV range is zero. The mass majority of PHEV owners drive in EV mode and focus on electric range rather than gas range.

**Comment by khpylon** [comment]
I just got my first log from a PHEV and this next was on my plans.  You'll be able to tap on the bottom progress bar to toggle between the two.

**Comment by khpylon** [comment]
A follow-up question; was the battery percentage value accurate before?

**Comment by FadingFox** [comment]
It was accurate.

**Comment by khpylon** [comment]
Thanks for the feedback.  This is being push out in version 2022.06.03 today.
