### ISSUE TITLE
Widget not updating enough

### ISSUE THREAD

**Issue by alangant** [khpylon/MachEWidget#21]
Using the Google Play widget, the last update is hours old.  The last alarm is only 3 minutes old.

I may have turned logging off/on a few minutes ago, so maybe not enough captured.

**Comment by alangant** [comment]
More log data:
[fsw_logfile-06-05-22_51_20.txt](https://github.com/khpylon/MachEWidget/files/8841780/fsw_logfile-06-05-22_51_20.txt)

**Comment by khpylon** [comment]
In the second log file, the alarm was running every 5 minutes and the app was reading data, but there was no updates to the data.  At 22:08, the app forced an update and at that point there was new data, and then no more updates until the end of the log.  I'm not seeing anything unusual.

**Comment by alangant** [comment]
Thanks. Perhaps in the documentation you can mention that the date of update is most recent change to Ford servers. I was confused.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by khpylon** [comment]
I added an entry to the FAQ explaining what this "Last refresh" is all about.  I probably should have done it sooner.

**Comment by alangant** [comment]
Great!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
