### ISSUE TITLE
OTA not displaying any info

### ISSUE THREAD

**Issue by ipeefreeli** [khpylon/MachEWidget#22]
Widget isn't displaying any OTA info. I've uninstalled the app and wiped the user data, logged back in and still no OTA data
[fsw_logfile-06-08-22_49_07.txt](https://github.com/khpylon/MachEWidget/files/8874813/fsw_logfile-06-08-22_49_07.txt)
.

**Comment by khpylon** [comment]
I see the app request the OTA info here.

`06/08 22:49:06 D OkHttp3: --> GET https://www.digitalservices.ford.com/owner/api/v2/ota/status?country=CAN&vin=3FMTK1SS6MM...`

But that's the last part of the log; I don't see a response from the server.  Maybe let the log app run longer (set the time interval between request for 5 minutes, then let it run an hour) and send that log?

**Comment by ipeefreeli** [comment]
I set the time interval for 5 minutes, and didn't realize it ran all night, but here's a longer log.

[fsw_logfile-06-10-11_22_32.txt](https://github.com/khpylon/MachEWidget/files/8880175/fsw_logfile-06-10-11_22_32.txt)

**Comment by khpylon** [comment]
That's much better.  Here's an example server response from the logfile:

`06/10 03:13:20 D OkHttp3: {"displayOTAStatusReport":"UserAllowed","ccsStatus":{"ccsConnectivity":"On","ccsVehicleData":"On"},"error":null,"fuseResponse":null,"tappsResponse":{"vin":"3FMTK1SS6MM","status":200,"vehicleInhibitStatus":null,"lifeCycleModeStatus":{"lifeCycleMode":"NORMAL","oemCorrelationId":"","vehicleDateTime":"2022-02-04T08:03:05.000Z","tappsDateTime":"2022-02-04T09:43:43.861863Z"},"asuActivationSchedule":{"scheduleType":"","dayOfWeekAndTime":null,"activationScheduleDaysOfWeek":[],"activationScheduleTimeOfDay":null,"oemCorrelationId":"","vehicleDateTime":"","tappsDateTime":""},"asuSettingsStatus":null,"version":"2.0.0"},"updatePendingState":null,"otaAlertStatus":null}
`

The fuseResponse is null, so there is no OTA information for the app to display.  Perhaps I'll change the message displayed in the widget to make this more clear.
