### ISSUE TITLE
Widget visually not updating (data is current)

### ISSUE THREAD

**Issue by CHeil402** [khpylon/MachEWidget#23]
In the widget, the data shown is outdated; however, if you triple-tap the last refresh time, the "last update" and "last alarm" timestamps are correct, just the information shown on the widget are outdated. Opening the widget and going back to the home screen updates the widget to show the latest information. Battery optimization is turned off. Not sure if this is a Nova Launcher issue, or something specific to the app.

Using Nova Prime 7 on Samsung S20+. Log file attached.
[fsw_logfile-06-13-16_11_11.txt](https://github.com/khpylon/MachEWidget/files/8894187/fsw_logfile-06-13-16_11_11.txt)

**Comment by khpylon** [comment]
I can confirm it's a bug.  What's happening is the app is finding two vehicles associated with the FordPass account, but one of them doesn't support status updates and so it's returning a failed status to the code that triggers the widget update.

**Comment by CHeil402** [comment]
It's a small sample size, but so far the latest beta seems to fix this issue today with all refreshes resulting in an updated widget.

**Comment by khpylon** [comment]
I've now added a few different changes to attack from multiple fronts: 1) vehicles with pre-2018 VINs are disabled by default (they can be re-enabled if desired), 2) if any vehicle's status is successfully updated then assume life is good, and 3) update the widget no matter what the status result says.
