### ISSUE TITLE
Refresh time off by 4 hours 

### ISSUE THREAD

**Issue by the-static** [khpylon/MachEWidget#25]
I've noticed my refresh time is 4 hours behind. I can force a manual refresh and if it is successful it shows exactly 4 hours behind the actual time of refresh. When I look at the time of refresh instead of how long ago it was, it shows the wrong time, also 4 hours off. So for example if I successfully refreshed at 11:37 am EDT it shows the last successful refresh as 4 hours ago, or 7:37 am EDT. I thought this might have been an issue for a while, but I couldn't really confirm until I had the ability to force a manual refresh.

**Comment by the-static** [comment]
Also, this is strangely intermittent, as of right now it seems to be showing the correct refresh time.

**Comment by khpylon** [comment]
Enable logging and upload them when you notice it happens.

**Comment by the-static** [comment]
Here's a log file I started when it was working fine and then I noticed this evening it was off again by 4 hours @ @
[fsw_logfile-07-02-20_15_58.txt](https://github.com/khpylon/MachEWidget/files/9033896/fsw_logfile-07-02-20_15_58.txt)

**Comment by khpylon** [comment]
The "last refresh" displayed is the contents of "lastRefresh" from the servers.  My understanding is that time is UTC, which would be 4 hours difference for you.  Here's what I found from the logfile:

Early on July 2, off by a lot

8:41:22am
    "lastRefresh": "07-01-2022 23:50:00",
    "lastModifiedDate": "07-01-2022 23:50:03",
    "serverTime": "07-02-2022 12:41:23",

That evening, about 4 hours off (as you noticed)

7:52:43pm
    "lastRefresh": "07-02-2022 19:43:26",
    "lastModifiedDate": "07-02-2022 23:43:29",
    "serverTime": "07-02-2022 23:52:43",

8:12:45pm
    "lastRefresh": "07-02-2022 19:57:13",
    "lastModifiedDate": "07-02-2022 23:57:16",
    "serverTime": "07-03-2022 00:12:45",

8:15:41pm
    "lastRefresh": "07-02-2022 20:15:24",
    "lastModifiedDate": "07-03-2022 00:15:27",
    "serverTime": "07-03-2022 00:15:41",

I compared this to mine and the lastRefresh time is 7 hours ahead of my local time, which would match UTC time:

July 3, 8:32:30am PDT:
    "lastRefresh": "07-03-2022 15:32:49",
    "lastModifiedDate": "07-03-2022 15:32:53",
    "serverTime": "07-03-2022 15:37:11",

When you say you're forcing a refresh, are you doing that in the app or in FordPass?  I didn't see anything in the logfile that looks like the app did a force refresh.  Also, when the app is showing the time off by 4 hours, what's FordPass say?

**Comment by the-static** [comment]
I have just been using the refresh button on the widget, so I don't know what the Ford pass app time says. But it's weird that sometimes when I do the refresh it can go from whatever previous time was there to 4 hours ago exactly, and other times it will go to 0 minutes ago. I agree it has something to do with my time zone, I just don't understand why it seemingly randomly accounts for that and then doesn't.

**Comment by khpylon** [comment]
The "refresh button on the widget"... do you mean the "Refresh" option in the three-dot menu?  If so, that just re-reads the last values from Ford's servers, which doesn't ask the vehicle to do anything.  In a recent release, I added a Settings option to enable "Enable forced refresh" which shows a new icon on the widget (a "refresh" icon) to actually force the server to ask the vehicle to refresh everything.  This is essentially the same thing which a  pull-down in the FordPass app does.

**Comment by the-static** [comment]
I'm talking about forced refreshes that get the truck to send new info to the server, the new feature you added that doesn't require Ford pass to do it.

**Comment by khpylon** [comment]
Ok.  I just didn't see anything that looked like forced refresh info in the logfile.

For what it's worth, I've seen the servers return old information (i.e., the lastRefresh time is earlier than a prior refresh).  When that happens, though, the app just ignores the status info.

**Comment by the-static** [comment]
I don't know if this helps, I have another log file I started when it was not doing it and stopped right after a forced refresh when it is doing it again. I also have screenshots of what I am talking about. In the screenshots the first image is what the widget looked like after I got home, about 28 minutes ago. The second shot is after a forced refresh and then third is just an app refresh (not forced, from the menu) 3 minutes later to show the time stays 4 hours off. When the app is not doing this, I can get the same exact results except that they aren't 4 hours off, they would show 28 minutes ago, 0 minutes ago and 3 minutes ago. Ford pass is useless it shows the last update was 16 hours ago.
![Screenshot_20220704-214604~3](https://user-images.githubusercontent.com/60277014/177234372-4f002007-742d-4791-90c8-6c637308f7f4.png)
![Screenshot_20220704-214634~2](https://user-images.githubusercontent.com/60277014/177234374-299adbbc-f25f-4f98-b101-edcf43a194ce.png)
![Screenshot_20220704-214942~2](https://user-images.githubusercontent.com/60277014/177234376-b54d95bd-6736-47e9-a8f6-d1af3d07b63b.png)

**Comment by the-static** [comment]
Here is an example of it working correctly and me doing the same thing as yesterday to get the time examples.
![Screenshot_20220705-142918~2](https://user-images.githubusercontent.com/60277014/177393154-26924d23-e35a-47d4-9e69-a38a982f5bb3.png)
![Screenshot_20220705-143002~2](https://user-images.githubusercontent.com/60277014/177393142-ca1eecf2-e6d5-48e7-a5ea-3bce7c29dcb1.png)
![Screenshot_20220705-143111](https://user-images.githubusercontent.com/60277014/177393145-5bae662a-3489-4e99-9efd-f9ab50c3e094.png)

**Comment by the-static** [comment]
Ironically, Ford Pass app now shows my last update was 12 hours ago, a 4 hour difference from last time when it was 16 hours.

**Comment by khpylon** [comment]
I got back to this today and looked at both sets of log files. Sometimes lastRefresh is off from the lastModifiedDate and serverTime by a few seconds, sometimes four hours.  It's something on Ford's side.  Is it still doing this?

**Comment by the-static** [comment]
I didn't drive the truck all week, so I haven't noticed, but I'll try to watch it this week.

**Comment by the-static** [comment]
Looks like it is still doing it. Ford pass app shows the same 4 hour discrepancy now too. I understand if it's a server thing there's not much you can do about it, thanks for looking into it anyway
