### ISSUE TITLE
Vehicle image samples for automatic color selection

### ISSUE THREAD

**Issue by khpylon** [khpylon/MachEWidget#26]
Instructions for locating the images:

1. Your phone needs to be rooted; there's no easy way otherwise to access the app's data
2. Using root, locate the app's internal data storage (on my phone, it's **/data/data/com.example.khughes,machewidget** for the GitHub version and **/data/data/org.khpylon.fswidget** for the Play Store version)
3. Copy the image file(s) under **shared_prefs/images** to somewhere else.
4. Rename the files **vehicle-color.png** (i.e., **mache-rapidred.png** , **f150supercab-iconicsilver.png**).  
Include the file name above the image, and check whether there's already another vehicle with the same color before posting.  

Don't resize the images if possible; I need them the original size.

mache-rapidred.png

![mache-rapidred](https://user-images.githubusercontent.com/18265404/179012665-0e34fddc-2af9-4dc2-b172-f71a51ccb70e.png)

**Comment by rdelar01** [comment]
Let me know if this works....I had captured this image from the Ford Configurator. It looks like the one in the widget.  Perhaps you can get the images from there as well. 

I was able to download your Mach E from the configurator and it looked like what you have here, same angle, too.  

![f150xltsupercrew-velocityblue](https://user-images.githubusercontent.com/109302890/179034890-b2dd940f-4200-4675-a14d-2c65e44c8aac.png)

**Comment by khpylon** [comment]
As long as it matches the one you see in the widget.  The size is different but the aspect ratio is the same.

**Comment by zhackwyatt** [comment]
Since I don't have root I can't do exactly what you ask. But, I think these may be the same thing.  This would be mache-infinite blue.

https://www.digitalservices.ford.com/fs/api/v2/vehicles/image/full?vin=3FMTK3R73MMA09234&year=2021&countryCode=USA&angle=4
https://www.digitalservices.ford.com/fs/api/v2/vehicles/image/full?vin=3FMTK3R73MMA09234&year=2021&countryCode=USA&angle=5

**Comment by khpylon** [comment]
Is this the angle you see in the full size widget? My code is going to look at the file stored, but it does not track the angle.

**Comment by rdelar01** [comment]
Using the handy URL above, "angle=1" is the one showing up in my widget...

![1](https://user-images.githubusercontent.com/109302890/179232531-73a6277b-f1c5-4c3b-8211-c81ed1cd170b.png)

**Comment by khpylon** [comment]
I should have added that the URLs @zhackwyatt posted are the ones used in the app.  It starts with angle=1 and keeps adding 1 until it gets an image (for some reason, some vehicles don't have all angles).

**Comment by zhackwyatt** [comment]
> Is this the angle you see in the full size widget? My code is going to look at the file stored, but it does not track the angle.

I actually don't see that image on the widget. Only in the Ford Pass app.  All I see is the Pony logo.

**Comment by khpylon** [comment]
> > Is this the angle you see in the full size widget? My code is going to look at the file stored, but it does not track the angle.
> 
> I actually don't see that image on the widget. Only in the Ford Pass app. All I see is the Pony logo.

That's somewhat oversight, somewhat planned (?). If the app fails to download them it never retries, assuming they're not there.  If you save and restore settings it will try to download them.

**Comment by zhackwyatt** [comment]
> > > Is this the angle you see in the full size widget? My code is going to look at the file stored, but it does not track the angle.
> > 
> > 
> > I actually don't see that image on the widget. Only in the Ford Pass app. All I see is the Pony logo.
> 
> That's somewhat oversight, somewhat planned (?). If the app fails to download them it never retries, assuming they're not there. If you save and restore settings it will try to download them.

I actually prefer the logo. I already have the car as part of the top down overview.

**Comment by khpylon** [comment]
> I actually prefer the logo. I already have the car as part of the top down overview.

I just added a control in settings to choose logo vs image.

**Comment by khpylon** [comment]
2022.07.16 commit includes this feature.  Thanks for the help figure out how to find images.
