### ISSUE TITLE
Add explanation about the colors/statuses of the notification icon

### ISSUE THREAD

**Issue by Eddict** [khpylon/MachEWidget#27]
in the info screen every icon's status and meaning is properly described and explained, but the notification icon 🔔 seems missing. cause mine is quite frequently red and I don't know exactly what is the underlying reason. or am I blind? 🙈

**Comment by khpylon** [comment]
It's the icon for the alarm system; green is armed, red is unarmed.  It's sort of buried in the second paragraph of the "Icon Information" section:

_A red alarm icon with the "Z" indicates the vehicle is in deep sleep._

I needed to convert the icons from Vector graphics to PNG so I could add them to the instructions, but was just lazy.  Thy're converted now so I can add a more illustrated description.

**Comment by Eddict** [comment]
ah ok, yes noticed that description. but mine was just red without a Z so wondered what that meant. still a bit weird though as I never turn off my alarm. that's indicating the motion sensor setting right?

**Comment by khpylon** [comment]
I honestly don't know if "alarm on" is with or without the motion sensors.  I assume it's the just the door alarm.  Green means the alarm is activated.  I've only recall seeing red when either someone is driving the car or it's unlocked.

**Comment by khpylon** [comment]
2022.07.16 version has updated description with pictures of the icons.
