### ISSUE TITLE
Vehicle color limitation

### ISSUE THREAD

**Issue by Eddict** [khpylon/MachEWidget#29]
thanks for adding the color feature, nice!
however, i can only select very colorful colors and nothing in the 'grey spectrum'. as my car is carbonized grey it would be nice to be able to select it. or editing the RGB value directly would also do/help.
Eddict

**Comment by khpylon** [comment]
You should be able to get grey colors by moving the circular selector to the center (near white) and then adjusting the light/dark with the horizontal slider below it.

**Comment by Eddict** [comment]
yes that worked, thanks!
