### ISSUE TITLE
Unknown OTA Status on widget

### ISSUE THREAD

**Issue by 51r-a1an** [khpylon/MachEWidget#32]
I had posted about this on the Android play store.  According to the log file, the fuseresponse field is null.  Is there a way to correct this?

(Note: log file removed for user privacy -- khpylon)

**Comment by khpylon** [comment]
> I had posted about this on the Android play store. According to the log file, the fuseresponse field is null. Is there a way to correct this?

Unfortunately, the only way to correct it is to receive a OTA.  Rumor has it that the last update is only visible for about three months, then it will revert to null.  My last OTA was May 2, so unfortunately I may be able to verify that in a few days.

**Comment by 51r-a1an** [comment]
ah, ok.  My truck is fully updated already, so that would make sense.

**Comment by khpylon** [comment]
In the next release, I'll change the message to something more descriptive.
