### ISSUE TITLE
Il widget non si aggiorna ..

### ISSUE THREAD

**Issue by manuelnodari** [khpylon/MachEWidget#33]
Il widget non si aggiorna .....o meglio si aggiorna quando vuole .

Le mie impostazioni di aggiornamento sono ogni 10 minuti , ma non lo fa .

**Comment by khpylon** [comment]
Be aware that new information is only displayed when the vehicle uploads something to Ford's servers.

If you turn on "Enable forced refresh" in Settings, you can then tap the yellow "refresh" icon to force an update, but you are limited how frequently you can do this to avoid draining the 12V battery.  

**Google Translation:**
Tieni presente che le nuove informazioni vengono visualizzate solo quando il veicolo carica qualcosa sui server Ford.

Se attivi "Abilita aggiornamento forzato" in Impostazioni, puoi toccare l'icona gialla "aggiorna" per forzare un aggiornamento, ma sei limitato alla frequenza con cui puoi farlo per evitare di scaricare la batteria da 12V.
