### ISSUE TITLE
OTA Info Not Updating

### ISSUE THREAD

**Issue by skiingj** [khpylon/MachEWidget#36]
Hello - The last 2-3 OTA updates have not registered in the app.  Let me know if you need anything from me.  Thanks for all the work you do.  Love the app.

**Comment by khpylon** [comment]
Yeah, this is a known bug since Ford changed the API.  Currently the app isn't even trying to pull from their servers to avoid taunting Happy Fun Ball.

I'm looking into a possible fix.

**Comment by skiingj** [comment]
Yikes.  Thanks for all the hard work,.

**Comment by khpylon** [comment]
I'm going to close this since I've not been able to find a new way to read the OTA status.  Which is a real bummer, it was one of my favorite parts of the app.

**Comment by skiingj** [comment]
Yes, big bummer.  Thanks for all the hard work.  My regular MME status has not updated in a couple months.  I love the app.
