### ISSUE TITLE
App is unable to get list of vehicles.

### ISSUE THREAD

**Issue by mikec85** [khpylon/MachEWidget#37]
Put my login info in and get a login successful message, but then get a popup unable to get vehicles.   I have uninstalled and reinstalled the app same issue.

The app has be working for me for several months and this just started, I think a few days ago. 
I am on a pixel 7 and have a F150 Lightning.

**Comment by khpylon** [comment]
Can you enable logging, go through the login process, then save the log and attach?

**Comment by mikec85** [comment]
fsw_logfile-12-09-18_04_01.txt

Log file attached.

Looks like this may be the explanation

<P>The requested resource has been temporarily moved. This usually occurs if there has been a mishandled redirect.
</P>

**Comment by khpylon** [comment]
The server is returning a 401 error for https://api.mps.ford.com/api/users.
`12/09 18:03:07 D OkHttp3: {"httpStatus":401,"status":402,"requestStatus":"CURRENT","error":{"statusContext":"CommonSDN","statusCode":"401","message":"Unknown response"},"lastRequested":"2022-12-10T00:03:07.174106Z","version":"1.0.0"}
`
It also seems that one a functions in NetworkCalls is being called with a null userId.  I'm not sure if these are related.

I assume you're on the F-150 forum.  Can you send me a DM there and include your settings file?  I'd like to see if I can dig a little deeper using some of your info.

**Comment by khpylon** [comment]
Nevermind; I just tried my own account and I'm getting the same error.  Ford must have changed the API again.... :(

**Comment by khpylon** [comment]
Actually, go ahead and save your settings.  Look through the JSON file and see if your vehicle's data is still there.  If so, send it to me in a DM and I'll see if I can reconstruct the original settings to work again.

**Comment by mikec85** [comment]
whats your handle on f150 forum?

**Comment by mikec85** [comment]
kennelh?

**Comment by khpylon** [comment]
yes, kennelh

**Comment by khpylon** [comment]
Should be fixed in the latest release.
