### ISSUE TITLE
Widget not updating for Broncos 

### ISSUE THREAD

**Issue by khpylon** [khpylon/MachEWidget#39]

**Comment by Jazerexy** [comment]
[fsw_logfile-01-06-21_17_28.txt](https://github.com/khpylon/MachEWidget/files/10365333/fsw_logfile-01-06-21_17_28.txt)

**Comment by khpylon** [comment]
The log file shows it's not updating, but it also doesn't show the login process.  Please start with that, following with a refresh, then upload that log file.  Thanks.

**Comment by Jazerexy** [comment]
fsw_logfile-01-07-14_23_07.txt

It now shows an update 17hrs ago after doing the re-log in and refresh.

**Comment by khpylon** [comment]
Yeah, I don't see anything abnormal.  Under Settings, make sure that "Hibernate app" disabled and that "Time between widget updates" isn't set to manual.  You can also triple tap on "Last refresh" on the widget and it will tell you (a) last time the servers received an update from your car and (b) the last time the app checked the servers.  The latter should change based on the time between updates you set.  Also, make sure "Battery optimization" is off.

**Comment by khpylon** [comment]
Has it been working for you the past few days, or are there still issues?

**Comment by Jazerexy** [comment]
It's still having issues. It seems to update if I re-log in and it'll show an update 2 to maybe 12 hrs old usually,  but otherwise it just sits there and doesn't update when I hit refresh.

**Comment by khpylon** [comment]
I checked the last log file you sent and verified that you have battery optimizations on, which will cause Android to "sleep" the app and not wake up when it's supposed to update.  [Follow the instructions here](https://github.com/khpylon/MachEWidget/blob/master/FAQ.md#q--why-does-the-app-seems-to-update-for-a-while-then-stop) to turn them off, then do a refresh, and see if that helps.

**Comment by Jazerexy** [comment]
Ohhh okay that would make sense. I just turned that off for the app.. will see if that helps. Thank you!

**Comment by Jazerexy** [comment]
Ok so I turned off the battery optimization but it still won't refresh unless I re log in.

**Comment by khpylon** [comment]
Ok... not sure what's going on.   Enable logging, set the time between widget updates to either 15 or 20 minutes, wait a few hours, then send me the log file.

Here also some other things you can try:
1)  After you've been logged in with the widget a hour or two, if it still isn't updating, go into FordPass and pull down on the main screen to have it force a vehicle update (you should see the spinning icon when it's doing that).  Then wait until the 15-20 minutes and see if the widget updates also.  
2) Triple tap on either the vehicle's hood (the two smaller widgets, where the hood is on the right) or the "Last refresh" text (the big widget withe the hood on the top).  You should see two messages pop up which say "Last update at..." and "Last alarm at...".  These are the timestamps of the latest update on Ford's servers, and the last alarm on the phone to update the widget contents.  If the last alarm is more than 15-20 minutes ago, or the last update is more recent than what the widget shows, that's a issue with the app.  If  the last alarm is "recent" and the update is close to the "Last refresh" on the widget, it's operating as normal.

**Comment by khpylon** [comment]
A new version has just been pushed out which fixed one problem like yours.

**Comment by khpylon** [comment]
Is the latest version (2023.01.13) working correctly?

**Comment by Jazerexy** [comment]
Since the update, it seems to refresh every so often on its own. Still won't refresh on demand, but I'm at least seeing something semi recent now.

**Comment by khpylon** [comment]
Ok.  Just to be sure you're aware, the app will pull data from Ford's servers based on the interval you set in Settings, but if the vehicle hasn't uploaded anything you won't see a change.

The best way I can recommend to check if it's working is when you don't see anything updating in the app, go into FordPass and force a refresh by either doing something like lock/unlock, windows up/down, or remote start, then waiting to see if the app shows the same thing in the next refresh.  If so, then it's working normally.

I'll leave this report open for you to close out in a few days.  Otherwise if I don't hear anything in a week or so I'll close myself.

**Comment by Jazerexy** [comment]
Ok will do, thanks so much for your quick/thorough help!
