### ISSUE TITLE
Bug - widget size

### ISSUE THREAD

**Issue by mporet** [khpylon/MachEWidget#4]
Widget footprint takes up almost an entire home screen. This is on Galaxy S20+
![Screenshot_20220206-224135_One UI Home](https://user-images.githubusercontent.com/32961547/152731007-8d3b5539-4cf1-4a7d-a807-e4fef63a1f81.jpg)

**Comment by mporet** [comment]
If it helps with debugging this issue I found that if I put it on a home screen that already has a large number of items, it will shrink its footprint by one row vertically

![Screenshot_20220206-224658_One UI Home](https://user-images.githubusercontent.com/32961547/152731670-d8132198-da91-4fbe-ae92-78aa176c3b4b.jpg)

**Comment by khpylon** [comment]
Thanks for the info.  Google doesn't give very detailed explanation of handling widget resizing but I think I've found something which works now.  I'll add it to the next release in a day or two.

**Comment by khpylon** [comment]
I pushed a new release a few minutes ago which should allow you to resize the widget (at least it lets me do it on my emulator and on my phone using the Pixel Launcher).  Let me know what you see.

**Comment by benk016** [comment]
Mine does this with todays update. The widgets fit into Rows of icons, SO it only snaps to the next size of icons. So there is blank space between the top and bottom of the app because the space it needs is smaller than 4 icon rows.

**Comment by khpylon** [comment]
The widget isn't exactly the height of a row of icons, so there is some unused space.  It was a pain to manually place everything before (I actually did it twice) but I'll put add an attempt to make it fit more closely in my TODO list.

**Comment by mporet** [comment]
Looks great! Can confirm it is resizable now. Thank you!  As mentioned above, it is not lining up with the grid but it is smaller
![Screenshot_20220208-132933_One UI Home](https://user-images.githubusercontent.com/32961547/153070540-90b1fb53-26f3-448f-a989-c5b703001f1c.jpg)

**Comment by khpylon** [comment]
The next release should have changes to the size of the widget.  My observations is that each launcher interpret the size of the widget independently.  I've resize to be close to what Pixel Launcher thinks is the "grid size", but Nova thinks it's totally different.  I'm going to use Pixel Launcher as my baseline so we'll just have to see how it works out for other launchers (like Samsung's).

**Comment by benk016** [comment]
This newest update did change the size on my Samsung S21. It now uses 3 rows instead of 4. 

![Screenshot_20220210-123246_One UI Home](https://user-images.githubusercontent.com/46057723/153473877-908db1b4-5d48-4d3c-aa26-0f78e5d11ad4.jpg)

**Comment by khpylon** [comment]
I'm planning to close this out unless anyone is still seeing something weird/wrong.

**Comment by mporet** [comment]
Been working for the last day for me!
