### ISSUE TITLE
Widget does not update

### ISSUE THREAD

**Issue by yuyangh** [khpylon/MachEWidget#40]
After log in, the widget can update successfully, but then the widget cannot update. 
Even force refresh cannot update the widget.
I have choosen automatically refresh with 20minutes interval

In the log, it shows a bunch of "STILL need to refresh token"
[fsw_logfile-01-11-08_08_48.txt](https://github.com/khpylon/MachEWidget/files/10395027/fsw_logfile-01-11-08_08_48.txt)

**Comment by khpylon** [comment]
I'm not sure but it appears the refresh is crashing.  When you open the app, does it save a fsw_logcat file?

Are you on macheforums.com?  If so, please send me a DM with your settings (under three-dot menu, choose "Save Settings", then attach the save JSON file in the DM.

**Comment by yuyangh** [comment]
Because I only click on `Save Logfile` once, so I only have 1 fsw_logfile. 
If I click on it, it will generate a new one for me.

Let me register macheforums and send you the JSON file

**Comment by khpylon** [comment]
On the macheforums.com, my ID is kennelh.

**Comment by yuyangh** [comment]
just sent a message to you on macheforums, thanks!

**Comment by khpylon** [comment]
The new version (2023.01.13) has just been pushed out.  Try it and see if it works better.

**Comment by yuyangh** [comment]
It works, thanks for the update!
