### ISSUE TITLE
Focus Electric support

### ISSUE THREAD

**Issue by cecil-t** [khpylon/MachEWidget#41]
Looking to get support for the Focus Electric.  Log files and photo attached.  Let me know if you need anything else!

![IMG_20171231_133152463_HDR](https://user-images.githubusercontent.com/25332104/230748565-989b089e-9942-4a2a-a6af-b454a557723e.jpg)
[fsw_logfile-04-08-20_29_32.txt](https://github.com/khpylon/MachEWidget/files/fsw_logfile-04-08-20_29_32.txt)
[fsw_logfile-04-02-11_52_31.txt](https://github.com/khpylon/MachEWidget/files/fsw_logfile-04-02-11_52_31.txt)

**Comment by khpylon** [comment]
Ok, I'll add support in the next release.  Your VIN indicates it's a 2017 model.  Is that correct?  I wasn't aware that Ford Connect worked in anything earlier than 2018.

**Comment by cecil-t** [comment]
Yes, this is a model year 2017.

The Focus Electric originally used an app called My Ford Mobile, but that
app was discontinued when 3G cellular was discontinued last year, and I had
to upgrade the modem in the car to support 4G.  Since then, they migrated
everyone from My Ford Mobile to the FordPass app, and pretty much all of
the functionality was restored.

Thank you for your efforts!

- Greg

**Comment by khpylon** [comment]
Ok, interesting.

Are you using the GitHub version of the app?  If so I can send you a test build to sideload.

**Comment by cecil-t** [comment]
I have it loaded now through the Play store, but I can side load for
testing if you make an APK.
Thanks

**Comment by khpylon** [comment]
Give [this](https://drive.google.com/file/d/1CmLO2rDhPn5GssXNXunAfXwNOlUQS5C3/view?usp=sharing) a try and let me know how it works.

**Comment by khpylon** [comment]
Sorry, changed the access permissions

**Comment by khpylon** [comment]
I took the JSON output from your logs and created a doppelganger of you vehicle to see how it displayed the data.  It pointed out some differences in the output from your Focus and most of the other vehicles.  Plus it looks like you don't have an TPMS data, and for some reason it doesn't know whether your hood is open or closed.  So made some more changes.

Give [this](https://drive.google.com/file/d/1CmLO2rDhPn5GssXNXunAfXwNOlUQS5C3/view?usp=sharing) new version a try and let me know how it works.

**Comment by cecil-t** [comment]
Thanks, yeah the hood was always red which was how I knew something was
wrong.  Now it seems OK (hood isn't red).  The location, last refresh, %
SOC and range are working.  I haven't been using it to issue commands
because I don't really want to get locked out by Ford.  I'll check the
doors and stuff later on.  I was only using the mid-size widget anyway so I
didn't even see the tire pressures.

**Comment by khpylon** [comment]
For whatever reason, the hood's state reports "Invalid" instead of "Closed" or "Ajar", so I changed the code to ignore that.  Might be interesting to see if the status changes when it's actually open.

I'll probably push this version out tonight or tomorrow, but in any case if you do notice anything weird just upload the log file here.

**Comment by cecil-t** [comment]
Okay I did some random things, opened all doors and hood and hatch, plugged in charging, and refreshed the Ford Pass app and your app in between, and attached is another log file.

On Ford Pass it only says "Monitoring" for tire pressures, apparently it can say "Low" as well if a tire is low, but I don't get individual pressures. See attached.

For the hood I don't believe there is even a sensor or switch, I don't think the car even knows if the hood is open.

Lastly, I don't think I've ever seen the bell / alarm icon be anything but green, even when the car is unlocked and open (which it is most of the time parked in the garage).  In Ford Pass I can send lock and unlock commands but it doesn't appear to show current lock status.

Hope that helps, thanks again.

![Screenshot_20230410_174053_FordPass](https://user-images.githubusercontent.com/25332104/231005316-b77159ae-d151-41d2-9c71-ec91f80651b4.jpg)

[fsw_logfile-04-10-17_41_25.txt](https://github.com/khpylon/MachEWidget/files/fsw_logfile-04-10-17_41_25.txt)

**Comment by cecil-t** [comment]
Confirmed that lock and alarm status always shows "Unlocked" and "Armed" regardless of vehicle state. I don't think it even has an alarm, and the current lock status definitely doesn't show in Ford Pass, though commands work.  One more log file attached with more activity after locking, preconditioning, and unlocking.  The preconditioning icon does turn yellow, so that works.
[fsw_logfile-04-10-17_54_04.txt](https://github.com/khpylon/MachEWidget/files/fsw_logfile-04-10-17_54_04.txt)

**Comment by khpylon** [comment]
Ok, thanks for the logfiles.  I'll see what I can do; it might be you become the outlier :)

I'm going to be out of town a few days so the version I push out in the next day or so probably will be the same as you're running, but once I can look at the logfiles there may be something I can do in future updates.  I'll leave this report open until that's settled.

**Comment by cecil-t** [comment]
Great, no problem.  I understand the car may simply not support some of
this functionality, but I appreciate anything you can do. Fundamentally
it's working.  Thanks again.

**Comment by khpylon** [comment]
I had a chance to look through the latest logfiles.  Both "alarm" and "lockStatus" always have a value "ERROR", so I suspect you're right about them not being supported.  The tire monitoring should show something when any tire shows something other than "STATUS_GOOD", but hopefully you'll never need to see that.

**Comment by cecil-t** [comment]
Great, thanks again for your help. Looks like that's about all we can get
out of this car.
