### ISSUE TITLE
2018 Fusion Energi VIN not supported

### ISSUE THREAD

**Issue by BillyCroan** [khpylon/MachEWidget#43]
Using the 2023-08-17 play store release, 3FA6P0SU7JR150135 is showing crossed out in the app with a note to post here for support.
My Fusion energy is a plug-in hybrid with a standard gas tank and the traction battery good for about 25 miles.

I like to keep it plugged in when parked to minimize trips to the gas station. And I'm thankful that this app lets me quickly see my state of charge and window and door positions and lock status a lot faster than Ford pass. If you had an in-app purchase to send some money your way I would love to as a thanks.  

Many months ago before Ford broke your widget the most recent time, he saved me from having a laptop stolen in public because I couldn't see my car but I could tell my window was open it went back out to close it before somebody stole my stuff!  Crisis averted!  

[fsw_logcat-08-19-09_46_24.txt](https://github.com/khpylon/MachEWidget/files/12386147/fsw_logcat-08-19-09_46_24.txt)

The above log file was one of many repeating which I suspected to do with a login problem.

The below to were generated after I told it to save log explicitly. 

[fsw_logcat-08-19-09_51_47.txt](https://github.com/khpylon/MachEWidget/files/12386150/fsw_logcat-08-19-09_51_47.txt)
[fsw_logfile-08-19-09_51_50.txt](https://github.com/khpylon/MachEWidget/files/12386152/fsw_logfile-08-19-09_51_50.txt)

Very curious what you make of these and I'm glad I can help support the project.

**Comment by khpylon** [comment]
The logcat file reports an issue that will be fixed in the next release.  The app log file doesn't have any real info in it, which is probably due to the app crashes.

I'll take a look into adding the Fusion Energi in the next release as well.  

The only way to donate to the project is through the Paypal link on the github page.  Since I don't have an image for the Fusion to use with the app, a small donation would help cover the cost of purchasing one.  If that's not important, I'll just use the Focus image.  You don't need to feel obligated if you're OK with a generic image.

**Comment by BillyCroan** [comment]
I don't really care about images at all myself but I'd be happy to send you
one of my car with the background photoshopped out if you want!  We just
washed it real good too.

I'll try to match the angles I see in screenshots and take one from both
sides so you have one with the charger port and one without it.

**Comment by khpylon** [comment]
Don't go to the trouble, I'd need SVG images.

**Comment by khpylon** [comment]
Just pushed a new version to the Play Store and Github.  Let me know if it doesn't work, and if it does work please enable logging, let it run to get an update, and upload the logfile so I can see what status info is being returned.

**Comment by khpylon** [comment]
Shoot, I was just looking over my available funds and forgot you already donated to the widget before.  Was that for this vehicle?

**Comment by BillyCroan** [comment]
Kind of...  This is the only ford I've had in a decade.  My donation was
really just a thank you for figuring out how all this works.  I didn't mean
to obligate you to one vehicle or another  If I'm the only fusion energi
user you have and its a lot of work to support, spend your time where you
think it makes the best difference for people.  I was just hoping that my
car wasn't that weird of an edge case.  I'll probably donate again in the
future when I have more cashflow too.

I'd love to have a working bash or php or pythin cli I an use to automate
things, like turning on the bedroom lights if I forgot to plug it in to
charge.

And maybe I'll try and write some of the code that I was dreaming up about
unsecured vehicle alerts.  The image/graphics really aren't something I
worry about.  It shows Mach E on my widget and that's fine with me.  It's
the features abilities I love and if I could help it crash less.  though it
did seem to settle down in the last couple hours.  I'll update it and get
back to you with more logs.

**Comment by khpylon** [comment]
I have some credits on a website that has the SVG images I use for the app... so this is a good justification to use them for someone who actually donated toward the project.  And I have to assume you're not the only Fusion user our there, you're just the first who actually reached out about support.

**Comment by khpylon** [comment]
I just pushed out 2023.08.21 with images for the Fusion.  Let me know how it works and it anything looks weird.

**Comment by khpylon** [comment]
I'm assuming all is good, so closing this out.  If not, just reopen the issue.
