### ISSUE TITLE
User-submitted data for new FordPass API

### ISSUE THREAD

**Issue by khpylon** [khpylon/MachEWidget#45]
Updating the app to Ford's 2024 API version will require changing how the status information for vehicles is processed.  I need user data from vehicles other than my Mach-E to figure out the new JSON format. 

1) Sideload the latest GitHub version (2024.01.24) of the app. 
2) On the app, go into "Settings" and turn on "Enable logging" (if you already have this turned on, toggle off then on to remove old log info).  Also be sure "Time between widget updates" is set for manual.
3) Under the three-bar menu select, select "FordPass Log-in" and log in with your FordPass account info.  If  the login works but you end up in the "Manage Vehicles" screen with no vehicle shown, add your vehicle.
4) Go back to the main screen and under the three-bar menu select "Save Logfile".  Close the app.
5) Check in your phone Download folder for the latest "fsw_logfile-xxxx" file.  If you want, download to your computer.
6) Open the file in a text editor and go to the end.  Work up back until you see a line containing "OkHttp3: <-- END HTTP (xxxxxx-byte body)".  Remove this and everything after it.  The very last line in the file now is the JSON data.  Remove everything before it.
8) Inside the JSON data, search for your VIN and remove the last 5 characters (your VIN may appear more than once).  Having the rest helps me identify the vehicle model and options.  You may also want to remove the GPS data under the tag "position".
9) Attached the edited file here.  Add your vehicle info in the comments.

**Comment by camattin** [comment]
Had to request access to file. Happy to provide the data for my 2021 F150 powerboost.

**Comment by khpylon** [comment]
Oops, I forgot to change the share access.  Give it another try.

**Comment by camattin** [comment]
The app reported a login failure but still actually did log me in. JSON file attached (I also masked my location in this).
[fp.json](https://github.com/khpylon/MachEWidget/files/13998954/fp.json)

**Comment by khpylon** [comment]
Thanks!
