### ISSUE TITLE
Crash on Focus Electric 

### ISSUE THREAD

**Issue by cecil-t** [khpylon/MachEWidget#46]
Just got latest update, widget doesn't open now.  Connected to a 2017 Focus Electric.  Attached are the log files.

[fsw_logcat-01-25-19_11_36.txt](https://github.com/khpylon/MachEWidget/files/14058948/fsw_logcat-01-25-19_11_36.txt)
[fsw_logcat-01-25-19_11_50.txt](https://github.com/khpylon/MachEWidget/files/14058950/fsw_logcat-01-25-19_11_50.txt)

**Comment by khpylon** [comment]
Thanks.  I have a fix for that but now something else has popped up.

**Comment by cecil-t** [comment]
I saw another update right after I posted this, here is the latest logs. They're all different sizes.

[fsw_logcat-01-25-19_11_36 (1).txt](https://github.com/khpylon/MachEWidget/files/14059398/fsw_logcat-01-25-19_11_36.1.txt)
[fsw_logcat-01-25-20_37_57.txt](https://github.com/khpylon/MachEWidget/files/14059399/fsw_logcat-01-25-20_37_57.txt)
[fsw_logcat-01-25-20_15_09.txt](https://github.com/khpylon/MachEWidget/files/14059400/fsw_logcat-01-25-20_15_09.txt)

**Comment by khpylon** [comment]
I just uploaded another version.  You may need to wipe data to get things happy, as the database format changed.  Let me know.

**Comment by cecil-t** [comment]
Okay, I had to clear app data, got logged back into the Ford Pass login, added VIN, then "Unable to retrieve vehicle data".

[fsw_logfile-01-25-22_27_15.txt](https://github.com/khpylon/MachEWidget/files/14059967/fsw_logfile-01-25-22_27_15.txt)

**Comment by khpylon** [comment]
Ok, thanks for uploading that log file.  The status info for your vehicle is much less than what I see on my car, probably because 2017 is such an early year for Ford doing Ford Connect status.  I'll let you know once I fix these issues.

**Comment by cecil-t** [comment]
Right on, thank you for your efforts.

**Comment by cecil-t** [comment]
In fairness the Ford Pass app is showing me less information right now, I can't even seem to see the location like it used to.  I'm really only seeing state of charge.

**Comment by khpylon** [comment]
If the latest releases fixed the problem, let me know.  If not, time to upload another logfile!

**Comment by cecil-t** [comment]
The one yesterday let me add the car and it's working, and I got another update just now.  I do get a random error about fuel level, see attached. It was doing this occasionally since I added the vehicle yesterday.
![Screenshot_20240128_132608_Ford Status Widget](https://github.com/khpylon/MachEWidget/assets/25332104/c78b43b1-dc6a-4596-9932-c7243f826bf8)

**Comment by cecil-t** [comment]
Here's a screenshot of the widget working
![Screenshot_20240128_133209_One UI Home](https://github.com/khpylon/MachEWidget/assets/25332104/0e54cb48-a1b8-4c0d-8467-14d89fb8c0c7)

**Comment by cecil-t** [comment]
...and the log file
[fsw_logfile-01-28-13_42_58.txt](https://github.com/khpylon/MachEWidget/files/14077327/fsw_logfile-01-28-13_42_58.txt)

**Comment by cecil-t** [comment]
Working on FFE now, closing
