### ISSUE TITLE
Unable to retrieve vehicle status

### ISSUE THREAD

**Issue by Bassaway** [khpylon/MachEWidget#47]
Error "Unable to retrieve vehicle status" following log-in and entering vehicle VIN.  Log file attached. 
[fsw_logfile-01-28-10_10_27.txt](https://github.com/khpylon/MachEWidget/files/14076833/fsw_logfile-01-28-10_10_27.txt)

**Comment by khpylon** [comment]
Thanks.  The app was able to get your truck's status info, but was expecting data that was missing.  Today's release will fix that.

**Comment by khpylon** [comment]
Let me know if today's release fixes the problem.

**Comment by Bassaway** [comment]
Everything is working!  Thanks!

**Comment by khpylon** [comment]
Great!
