### ISSUE TITLE
Unable to get fuel level on Ford Lightning 

### ISSUE THREAD

**Issue by AlRFORCE1** [khpylon/MachEWidget#48]
On each refresh I have this pop up. I drive a Ford Lightning, so it has no fuel. =)

![Screenshot_20240128_130755_Ford Status Widget](https://github.com/khpylon/MachEWidget/assets/44093483/54994b26-f356-427a-a03b-5f6db840fdd2)

Let me know if you need anything else or don't get the picture. Amazing work!!!

**Comment by AlRFORCE1** [comment]
[fsw_logfile-01-28-13_29_27.txt](https://github.com/khpylon/MachEWidget/files/14077465/fsw_logfile-01-28-13_29_27.txt)

**Comment by AlRFORCE1** [comment]
Update: I should have read all the way through the other reported issue because someone mentioned this already.

https://github.com/khpylon/MachEWidget/issues/46#issuecomment-1913683770

**Comment by AlRFORCE1** [comment]
It looks like the other issue has been closed for the FFE model, but its still happening in the Ford F150 Lightning

**Comment by khpylon** [comment]
The Mach-E and Lightning should be responding the same way.  I put in a different check for the next release, but in the meantime if you remove your vehicle and then add it again does it work or do the same thing?

**Comment by AlRFORCE1** [comment]
I tried removing and re-adding the vehicle from the menu, buy that didn't fix it. I also tried completely uninstalling and reinstalling the app, but after setting it up I'm still same notification. Thanks for everything you do!

**Comment by khpylon** [comment]
Are you on the F-150 forum (https://www.f150gen14.com/)?  I may need to have you send me a copy of your settings but I this isn't a good place to post that information.  If not, send it as an attachment to my e-mail (khpylon@gmail.com)

**Comment by AlRFORCE1** [comment]
Sounds good. The truck has been at the shop the past couple of weeks. I'll give it a try when I get it back.

**Comment by AlRFORCE1** [comment]
Finally got the truck back today. I'll let you know if it's still an issue.

**Comment by AlRFORCE1** [comment]
This issue appears to be resolved!
