### ISSUE TITLE
Cannot add Maverick VIN (that used to work)

### ISSUE THREAD

**Issue by daemonic3** [khpylon/MachEWidget#49]
I am unable to add my Ford Maverick to recent version (Jan28 build).  It had worked up through October for sure, when the APIs were all working (had the cyber orange image and everything).

I get "unable to retrieve vehicle information" when trying to add vehicle.  The app knows the VIN is for a Maverick though.

Attaching log, enabled right before trying to add, and stopped right after.
[fsw_logfile-01-30-14_46_03.txt](https://github.com/khpylon/MachEWidget/files/14105260/fsw_logfile-01-30-14_46_03.txt)

**Comment by khpylon** [comment]
So if this is all good now, I'll close the issue.

**Comment by daemonic3** [comment]
All good! Today's update even gave me my white Mach E and cyber orange mav,
but my f150 is still clear! Go figure...

Thanks Dr Hughes!
-T

**Comment by khpylon** [comment]
We're on the forums... it's just Ken here :)
