### ISSUE TITLE
Distance Units Not correct

### ISSUE THREAD

**Issue by benk016** [khpylon/MachEWidget#5]
The widget for me is not respecting my units set in FordPass. I only see km for distance instead of miles. 

![Screenshot_20220208-115849_One UI Home](https://user-images.githubusercontent.com/46057723/153047827-9b49cf13-8a2c-4977-8d98-801b21d3ccb2.jpg)

**Comment by khpylon** [comment]
The next release will allow you to choose units.

For future reference, the app picks up information from your profile on Ford's servers.  Some of that info can be changed in FordPass under Account -> Settings -> Units of Measure.  If you're seeing something odd, you may need to change those settings then log into the app again (they're only read on a log-in, not during status updates).
