### ISSUE TITLE
2017 Fusion-  widget will not refresh or update.

### ISSUE THREAD

**Issue by 3673FusionFan** [khpylon/MachEWidget#50]
Thank you for your hard work and this app.!  I have a 2017 Ford Fusion Enrgi with 4G modem update.  Widget was working with the lock status update version about 5 days prior to the 2024.02.09-12  DC charging update (current) version.  Any way to get the APK prior version or fix for the Fusion?  Current version is not refreshing the widget.  Thank you!

**Comment by khpylon** [comment]
You can find all the prior releases here:
https://github.com/khpylon/MachEWidget/commits/master/app/github/release
But in the meantime, if you upload a logfile I try to figure out why yours stopped working so I can fix it.

**Comment by 3673FusionFan** [comment]
Thank you! Super fast response- thanks.  Here is the log file.
[fsw_logfile-02-10-16_58_08.txt](https://github.com/khpylon/MachEWidget/files/14230943/fsw_logfile-02-10-16_58_08.txt)

**Comment by khpylon** [comment]
Ok, that is very helpful.   I assume the Energi is a plug-in hybrid?  The JSON status shows charging in progress but it's missing some of the other fields I was expecting, hence the problem.

**Comment by 3673FusionFan** [comment]
Happy to help.   Yes,  it is a plug-in hybrid.

**Comment by 3673FusionFan** [comment]
I updated the app to the current version- 2024-02-11-13 and it is now refreshing.  Thank you!   Here is the log file if you are interested.   
[fsw_logfile-02-11-16_55_10.txt](https://github.com/khpylon/MachEWidget/files/14234640/fsw_logfile-02-11-16_55_10.txt)

**Comment by khpylon** [comment]
Glad to hear that fixed it. There's a lot to learn still about their new API.
