### ISSUE TITLE
VIN strikethrough on Mach-e

### ISSUE THREAD

**Issue by b177y3** [khpylon/MachEWidget#52]
When I add my Mach-e the VIN has a strikethrough. Everything seems to be working. Instructions say to start a new issue. Log file attached.

[fsw_logfile-03-03-21_19_48.txt](https://github.com/khpylon/MachEWidget/files/14476919/fsw_logfile-03-03-21_19_48.txt)

**Comment by khpylon** [comment]
Please send me a another log file; the previous one has no status information for me to review.  Just to be sure, select "Refresh" in the three-dot menu to force one.

Also, which country are you in?  The app should recognize North American and European vehicles, so I'm suspecting you're in or near Australia?

**Comment by b177y3** [comment]
I am in the USA. 2023 Mach-e California Rt 1 delivered Sept 2023.

I thought the log files were too small.... The attached file is much larger, following your refresh instructions.

Sent a screenshot of the strikethrough VIN too.

Thank you for the cool widget, I hope this helps with debugging!

Bill

------------
William "Bill" Miano
***@***.***

Sent from Proton Mail mobile

03/04 02:48:23 D OkHttp3: {"updateTime":"2024-03-04T10:47:56Z","vehicleId":"8292fe65-bdcd-4284-aae6-83d109fc09dc","vin":"3FMTK2SU2PMAxxxxx",....

**Comment by khpylon** [comment]
Ah, I see.  Ford changed the VIN designation for the CA Route 1 (digits 5-7 used to be "K2R", yours is "K2S").  I'll put in a fix for that in the next version.

**Comment by khpylon** [comment]
Actually, I hadn't noticed Ford added AWD models for the CA Route 1 in 2022.  The app was only looking for RWD models.  My bad!

**Comment by b177y3** [comment]
Awesome! Sounds like a quick fix.

I will actually be away from the car and out of cell service for a month so I won't be able to verify a fix on the widget until April, unless you send out a new version today or tomorrow.

Thank you again!

------------
William "Bill" Miano
***@***.***

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by khpylon** [comment]
I pushed it out  about an hour ago, so it is up on the Play Store and GitHub.

**Comment by b177y3** [comment]
Works perfectly. No more strikethrough.

Thank you!

------------
William "Bill" Miano
***@***.***

Sent from Proton Mail mobile

-------- Original Message --------
