### ISSUE TITLE
2019 Fusion Hybrid- Crossed out VIN

### ISSUE THREAD

**Issue by KimjaKay** [khpylon/MachEWidget#53]
Hello.  First off I want to say I really appreciate what you're doing here and this app. Although I know it's still in the works,  the concept and idea behind it is absolutely fantastic! As I was exploring,  I noticed my VIN was crossed out and I read to put in a ticket for an issue, so here I am. I've attached my log file in hopes it helps. Also the app is unable to log in to my Ford Pass but I am assuming that's for many until the API conflict is solved,  correct?  Other than those two things, I've noticed that when I go to triple tap for the refresh info,  I'm unable to get a double, let alone triple tap in before the window pops up that explains the functions of the widget. I look forward to hearing back from you. 

**Thanks so much again for your work.  :)** 

[fsw_logfile-05-18-01_56_54.txt](https://github.com/khpylon/MachEWidget/files/15360450/fsw_logfile-05-18-01_56_54.txt)

**Comment by khpylon** [comment]
I'd not tried logging in recently, and it looks like Ford has changed server URLs.  I'll implement changes that the folds over at FordPass Home Automation implemented to see if that fixes it for now.  I'll also see about adding in your VIN to the list of vehicles.

**Comment by khpylon** [comment]
So the app isn't recognizing your car because I don't have a Fusion hybrid with the letters "P0M" in the VIN.  I have Fusion S Hybrid (POU) and Fusion SE Hybrid (POL).  Is yours something else?

**Comment by KimjaKay** [comment]
Oh okay that makes sense.  Yes I have the Fusion SEL Hybrid

**Comment by khpylon** [comment]
The version pushed out today should recognize the VIN now, even if nobody can log in.  If that's the case, you can close this report out.

**Comment by KimjaKay** [comment]
Perfect. 👏👏👏 Everything works with my VIN now.  Thanks again.  Keep up the great work!!!
