### ISSUE TITLE
Vehicle not fully recognized (VIN Striked thru)

### ISSUE THREAD

**Issue by BMiot49** [khpylon/MachEWidget#54]
Hi there,

I remember (I think) I saw somewhere that if a VIN was striked it was possible to ask to unlock it by providing the beginning of the VIN.
Am I right ?
If yes, can you, please, do something for me ?

My VIN is WF0TK1E47PMA9(XXXX).

I'm in France, please let me also know if I can be of any help with french traduction.

Best Regards,
Bertrand.

**Comment by khpylon** [comment]
What is the model of your vehicle?  Currently the app only recognizes the Kuga, Puma, and Focus.

**Comment by BMiot49** [comment]
Oups ! sorry I forgot to mention…

 

This is a 2023 Mach e

 

 

De : khpylon ***@***.***> 
Envoyé : vendredi 24 mai 2024 17:13
À : khpylon/MachEWidget ***@***.***>
Cc : BMiot49 ***@***.***>; Author ***@***.***>
Objet : Re: [khpylon/MachEWidget] Vehicule not fully recognized (VIN Striked thru) (Issue #54)

 

What is the model of your vehicle? Currently the app only recognizes the Kuga, Puma, and Focus.

**Comment by khpylon** [comment]
That's very interesting; yours is the first Mach-E I've seen with a European VIN.  Which type is it (Select, Premium, GT, RWD, AWD)? 

Edit: sorry, don't know why I said that.  _Any_ VIN starting with "WF0" I assume is a Mach-E.  I'll take a look to see if I can find something.

**Comment by khpylon** [comment]
Actually it would helpful to look at your application's settings.  Can you save them, copy to your computer, edit remove your refreshToken value and GPS location (if desired), then attach here?

**Comment by BMiot49** [comment]
Hi @khpylon ,

I think the range can be different between countries.
I attach here the brochure of the french models so you can eventually compare.
[BRO-Ford_Mustang_Mach_E 2023.pdf](https://github.com/khpylon/MachEWidget/files/15484857/BRO-Ford_Mustang_Mach_E.2023.pdf)

Mine is : 
Mach-e Standard Range (RWD) (Not Premium, not GT)
72,6kWh Battery
Pack Technology+
White Space

Hope it helps!
BR, Bertrand.

**Comment by BMiot49** [comment]
Hi @khpylon,
fsw_settings-05-29-15_17_33.json

Additionnally, I join my app settings file.

**Comment by khpylon** [comment]
> Hi @khpylon ,
> 
> I think the range can be different between countries. I attach here the brochure of the french models so you can eventually compare. [BRO-Ford_Mustang_Mach_E 2023.pdf](https://github.com/khpylon/MachEWidget/files/15484857/BRO-Ford_Mustang_Mach_E.2023.pdf)
> 
> Mine is : Mach-e Standard Range (RWD) (Not Premium, not GT) 72,6kWh Battery Pack Technology+ White Space
> 
> Hope it helps! BR, Bertrand.

Thanks for the info.  I know Ford has changed some of the model line-ups, but in Europe I'd only seen one variant of the Mach-E.  Maybe I need to go back and look more closely at the VINs.

**Comment by khpylon** [comment]
OK, found the reason for the mark-through.  It's a simple fix for now, but I'd like to figure out more about the European VINs to see if I can pull out the specific variant.

**Comment by BMiot49** [comment]
Great, just let me know if I can be of any help. Le 29 mai 2024 20:16, khpylon ***@***.***> a écrit :
OK, found the reason for the mark-through.  It's a simple fix for now, but I'd like to figure out more about the European VINs to see if I can pull out the specific variant.

**Comment by khpylon** [comment]
Pushing out a new version (2024.05.29-17) in the next few hours.  If that fixes the issue, you can go ahead and close this issue.

**Comment by BMiot49** [comment]
Thank You @khpylon !

I close it.
