### ISSUE TITLE
F150

### ISSUE THREAD

**Issue by the-static** [khpylon/MachEWidget#8]
I have a 21 f150, I logged into the widget and can see a lot of info. I'd be happy to test some f150 specific updates if you are interested in pursuing that, I know the tonesto iOS widget it very popular on the f150 forum, so the user base is there.

**Comment by khpylon** [comment]
I'm not opposed to that, but I'd need for owners to send me the JSON output for the status and OT so I know what info it outputs that's different from the Mach-E.

**Comment by the-static** [comment]
> I'm not opposed to that, but I'd need for owners to send me the JSON output for the status and OT so I know what info it outputs that's different from the Mach-E.

I'd also be willing to help with that, if you don't mind pointing me in the right direction. Is that something I can send from your app, or will I need something else to get that?

**Comment by khpylon** [comment]
There are a few ways you could get the information.  
1) I wrote a script in Python which pulls the status and OTA info.  It can output the raw JSON info.
2) If your phone is rooted, you can grab your VIN file in /data/data/com.example.khughes.machewidget/shared_prefs and send it to me (the JSON is stored as a compressed string, but that's not a problem)
3) I can send you a version of the app which writes the http transfers to android's logs, which you can then extract using adb.

**Comment by the-static** [comment]
My current phone is not rooted, but I have an older rooted phone. I'll get this set up on that and see what I can get for you.

**Comment by khpylon** [comment]
If you send me a DM on the forums, I'll send you a link to a version of the app which will output the JSON to logs, then you can extract with adb.

**Comment by the-static** [comment]
Hey, so I'm looking on my rooted phone but I am not seeing that directory. I'm not on the mache forum, so I cant send you a message there if that's where you're talking about.

**Comment by khpylon** [comment]
Sorry, typo.  It's /data/data/com.example.khughes.machewidget/shared_prefs

**Comment by the-static** [comment]
Yeah I only have 2 directories in the /data/data folder and neither are that. I did find something in the /data_mirror/data-ce/null/0/com.example.khughes.machewidget/shared_prefs folder that looks like what you're asking for, there's a .xml file with my vin number as the name.

**Comment by khpylon** [comment]
Yep, that's the one.  Can you rename to data.xml and upload it here?

**Comment by the-static** [comment]
[data.txt](https://github.com/khpylon/MachEWidget/files/8112024/data.txt)
It wouldn't take an xml, so I changed it to txt. Let me know if that works

**Comment by khpylon** [comment]
That's perfect; I was able to get the JSON for both things.  Thanks!

**Comment by the-static** [comment]
Ok, great! And I can confirm that my truck is not a 4 door, so it will not report rear window status, I don't know if the 4 door f150 will. I can see Alarm, Lock, tmps, front 2 windows, miles to empty, odo, location, OTA Status, and the lock and engine start toggles work. Charge status and battery level show nothing, but I do see voltage at 12 for LVB.

**Comment by khpylon** [comment]
I joined the f150gen14 forums (I'm assuming that's the one you're on).  When I get something for people to test out I'll post it there.  In the meantime, if you DM me there (kennelh) I can get a test version for you to try later.

**Comment by the-static** [comment]
> I joined the f150gen14 forums (I'm assuming that's the one you're on). When I get something for people to test out I'll post it there. In the meantime, if you DM me there (kennelh) I can get a test version for you to try later.

Sounds good, message sent.
